### ISSUE TITLE
Replacement of Umlauts: is this necessary

### ISSUE THREAD

**Issue by lucaboesch** [TUM-MZ/moodle-block_material-download#11]
In download_materialien.php you define a pattern from which you then do str_replace in file and directory names sometimes
`$ersetzen_mit = array('Ä', 'ä', 'Ö', 'ö', 'Ü', 'ü', 'ß', ' ', '/');`
`$ersetzt = array('Ae', 'ae', 'Oe', 'oe', 'Ue', 'ue', 'ss', '_', '-');`
I wonder: isn't just calling the function clean_filename() enough?
IMHO operating systems nowadays should be able to work with utf8 file and directory names.
At least some other Moodle functions like when you're downloading files handed in with the assignment activity, the file names pop out UTF8 encoded.

**Comment by alendit** [comment]
Fixed by your pull request.
