### ISSUE TITLE
support for different types of databases?

### ISSUE THREAD

**Issue by mwuttke** [TUM-MZ/moodle-block_material-download#4]
Hello,

I am looking for years a plugin like this. Please could you provide this plugin also with support of other types of databases wich moodle supports, not only mysql?

That would be great.

Thanks & Greetings,
Michael

**Comment by tkorner** [comment]
I completely agree

**Comment by tkorner** [comment]
btw. I would be happy, if the code documentation (readme, versions...) would be extended... :-)

**Comment by mwuttke** [comment]
and a db/access.php would also helpful ... ;-)

**Comment by nino2205** [comment]
Hi there,

very nice tool! I also found some debug-warnings with PHP 5.5

<pre>
Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future
</pre>

It would be nice to use the moodle dml-api instead, you can kill two birds with one stone.

**Comment by alendit** [comment]
Hi,

thanks for your reports. We'll definitely switch to Moodle's data access
API soon, too allow usage with different DB backends.

**Comment by mwuttke** [comment]
Hello,

I've installed your plugin and tried to ad it as a block in one course and I've got the following error message:

Debug info: ERROR: syntax error at or near "."
LINE 1: SELECT `mdl_course_modules`.`id` FROM `mdl_course_modules` W...
^
SELECT `mdl_course_modules`.`id` FROM `mdl_course_modules` WHERE `mdl_course_modules`.`course` = '2907' AND ( `mdl_course_modules`.`module` = '14' OR `mdl_course_modules`.`module` = '6' )
[array (
)]
Error code: dmlreadexception
Stack trace:

```
line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 68 of /blocks/material_download/block_material_download.php: call to pgsql_native_moodle_database->get_records_sql()
line 288 of /blocks/moodleblock.class.php: call to block_material_download->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 971 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1023 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 392 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 45 of /theme/clean/layout/columns3.php: call to core_renderer->standard_head_html()
line 915 of /lib/outputrenderers.php: call to include()
line 845 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 245 of /course/view.php: call to core_renderer->header()
```

I am using moodle 2.8.6, postgresql 9.4 and php 5.5.12/5.6.9.

Thnaks & Greetings,
Michael

**Comment by alendit** [comment]
Hi, thanks for your feedback. Unfortunately, I don't have a pgsql setup at hand, can you please test the new version?

**Comment by mwuttke** [comment]
Now it works as expected. ;-)

Thanks a lot! 

Greetings,
Michael
