### ISSUE TITLE
empty zip file

### ISSUE THREAD

**Issue by danbuntu** [TUM-MZ/moodle-block_material-download#7]
I've just installed this on moodle 2.7 and I'm getting the block.

When I click on download all files I get an empty zip file downloaded.

What am I missing please?

**Comment by alendit** [comment]
Can you backup the course in question and post it somewhere so I can check? If the course contains sensitive information, you could create a new one as minimal example to demonstrate the problem.

**Comment by danbuntu** [comment]
Hi

A backup is here:

https://midkentcollege-my.sharepoint.com/personal/dan_attwood_midkent_ac_uk/_layouts/15/guestaccess.aspx?guestaccesstoken=zqlzgpfhhz0uZfEXdmVWanFuvAIOv9YhNWneco97W1M%3d&docid=037c32ae8f10a44afae2b932f48ee7ad0

**Comment by alendit** [comment]
Thanks, I'll look into it.

**Comment by danbuntu** [comment]
Hi have you had any luck in debugging this?

**Comment by alendit** [comment]
Hi, I just tried your course with Moodle 2.7.12 and 3.0.2 and both worked fine. I've got a zip with 71 files.

Do you happen to know what your database prefix is (can be seen in `config.php` under `$CFG->prefix`. If it's not default (`_mdl`), it breaks right now. I'll fix it shortly.

**Comment by alendit** [comment]
If your prefix wasn't `_mdl`, bd7d79e should fix it. If it was `_mdl` then we'll have to think further.

**Comment by danbuntu** [comment]
by prefix is mdl_

My understanding is that 'mdl_' is the default. Can't you use $CFG->prefix though t automatically pick prefix from the config.php

**Comment by alendit** [comment]
I've mistyped, I've meant `mdl_`, just like you have. 

Ok, so it means the prefix wasn't the problem. Can you give more information about your setup, like PHP version, the database you use, your webserver (Apache or Nginx).

And could you try to restore the course from the backup you created as a new course and try to download the files from the new course?

**Comment by danbuntu** [comment]
I restored a backup as you suggested and that worked. Could this be something to do with the legacy file system? Our moodle was upgrade from 1.9 > 2.0. I believe this was an original 1.9 course.

My setup is Ubuntu 14.04, Apache and mysql, moodle 2.7.

**Comment by alendit** [comment]
I'm not sure what was going on at the time of 1.9>2.0 upgrade, sorry. It may well be an issue with the old format.

Can you try restoring the course from the backup as the same course? This may solve the issue altogether.

**Comment by danbuntu** [comment]
We'll i'll be dammed. I've just gone back to the original course I was trying to export and that is now working fine.

**Comment by alendit** [comment]
Have you updated `material-download` block in-between?

**Comment by alendit** [comment]
Closing, since the problem seems to have solved itself.
