### ISSUE TITLE
Einzelne Abschnitte downloaden  (Moodle 3.0)

### ISSUE THREAD

**Issue by merxim** [TUM-MZ/moodle-block_material-download#9]
Mehrere Arbeitsmaterialen in vielen Wochen ->

![download individually](https://cloud.githubusercontent.com/assets/15237875/13351511/5a4de0cc-dc87-11e5-9e1f-d957aa2ef6e7.png)

**Comment by alendit** [comment]
Schicke bitte den Link zum Testkurs

**Comment by merxim** [comment]
https://training.moodle.tum.de/course/view.php?id=20

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi
